// Generated by gencpp from file perception_msgs/ts_3DPose.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_TS_3DPOSE_H
#define PERCEPTION_MSGS_MESSAGE_TS_3DPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct ts_3DPose_
{
  typedef ts_3DPose_<ContainerAllocator> Type;

  ts_3DPose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)  {
    }
  ts_3DPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _psi_type;
  _psi_type psi;





  typedef boost::shared_ptr< ::perception_msgs::ts_3DPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::ts_3DPose_<ContainerAllocator> const> ConstPtr;

}; // struct ts_3DPose_

typedef ::perception_msgs::ts_3DPose_<std::allocator<void> > ts_3DPose;

typedef boost::shared_ptr< ::perception_msgs::ts_3DPose > ts_3DPosePtr;
typedef boost::shared_ptr< ::perception_msgs::ts_3DPose const> ts_3DPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::ts_3DPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::ts_3DPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'perception_msgs': ['/home/leiyubiao/dalian/src/tracking/messages/perception_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_3DPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_3DPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_3DPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28833ad46fe44d5123a6573471f79229";
  }

  static const char* value(const ::perception_msgs::ts_3DPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28833ad46fe44d51ULL;
  static const uint64_t static_value2 = 0x23a6573471f79229ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/ts_3DPose";
  }

  static const char* value(const ::perception_msgs::ts_3DPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 phi\n\
float64 theta\n\
float64 psi\n\
";
  }

  static const char* value(const ::perception_msgs::ts_3DPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ts_3DPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::ts_3DPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::ts_3DPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_TS_3DPOSE_H
