// Generated by gencpp from file perception_msgs/ts_ObjectList.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_TS_OBJECTLIST_H
#define PERCEPTION_MSGS_MESSAGE_TS_OBJECTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_msgs/ts_Object.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct ts_ObjectList_
{
  typedef ts_ObjectList_<ContainerAllocator> Type;

  ts_ObjectList_()
    : header()
    , sensor()
    , objects()  {
    }
  ts_ObjectList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_type;
  _sensor_type sensor;

   typedef std::vector< ::perception_msgs::ts_Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::ts_Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::perception_msgs::ts_ObjectList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::ts_ObjectList_<ContainerAllocator> const> ConstPtr;

}; // struct ts_ObjectList_

typedef ::perception_msgs::ts_ObjectList_<std::allocator<void> > ts_ObjectList;

typedef boost::shared_ptr< ::perception_msgs::ts_ObjectList > ts_ObjectListPtr;
typedef boost::shared_ptr< ::perception_msgs::ts_ObjectList const> ts_ObjectListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::ts_ObjectList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/leiyubiao/dalian/src/tracking/messages/perception_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_ObjectList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_ObjectList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_ObjectList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ada8e9075049a493d6740fe5140a812a";
  }

  static const char* value(const ::perception_msgs::ts_ObjectList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xada8e9075049a493ULL;
  static const uint64_t static_value2 = 0xd6740fe5140a812aULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/ts_ObjectList";
  }

  static const char* value(const ::perception_msgs::ts_ObjectList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string sensor\n\
ts_Object[] objects\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: perception_msgs/ts_Object\n\
\n\
int32 object_id\n\
\n\
ts_3DPose rel_pose\n\
\n\
bool geometry_state\n\
ts_Geometry geometry\n\
\n\
================================================================================\n\
MSG: perception_msgs/ts_3DPose\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 phi\n\
float64 theta\n\
float64 psi\n\
\n\
================================================================================\n\
MSG: perception_msgs/ts_Geometry\n\
float64 length\n\
float64 width\n\
float64 height\n\
";
  }

  static const char* value(const ::perception_msgs::ts_ObjectList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ts_ObjectList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::ts_ObjectList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::ts_ObjectList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::ts_Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_TS_OBJECTLIST_H
