# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_msgs/control_req.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class control_req(genpy.Message):
  _md5sum = "f755ac002e0891a7af88d03d37522ace"
  _type = "control_msgs/control_req"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 Vel_req
float64 Angle_req
int32 Gear_req
# 0x0:P 0x1:R 0x2:N 0x3:D
"""
  __slots__ = ['Vel_req','Angle_req','Gear_req']
  _slot_types = ['float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Vel_req,Angle_req,Gear_req

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(control_req, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Vel_req is None:
        self.Vel_req = 0.
      if self.Angle_req is None:
        self.Angle_req = 0.
      if self.Gear_req is None:
        self.Gear_req = 0
    else:
      self.Vel_req = 0.
      self.Angle_req = 0.
      self.Gear_req = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2di().pack(_x.Vel_req, _x.Angle_req, _x.Gear_req))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.Vel_req, _x.Angle_req, _x.Gear_req,) = _get_struct_2di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2di().pack(_x.Vel_req, _x.Angle_req, _x.Gear_req))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.Vel_req, _x.Angle_req, _x.Gear_req,) = _get_struct_2di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2di = None
def _get_struct_2di():
    global _struct_2di
    if _struct_2di is None:
        _struct_2di = struct.Struct("<2di")
    return _struct_2di
