// Generated by gencpp from file control_msgs/control_req.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_CONTROL_REQ_H
#define CONTROL_MSGS_MESSAGE_CONTROL_REQ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_msgs
{
template <class ContainerAllocator>
struct control_req_
{
  typedef control_req_<ContainerAllocator> Type;

  control_req_()
    : Vel_req(0.0)
    , Angle_req(0.0)
    , Gear_req(0)  {
    }
  control_req_(const ContainerAllocator& _alloc)
    : Vel_req(0.0)
    , Angle_req(0.0)
    , Gear_req(0)  {
  (void)_alloc;
    }



   typedef double _Vel_req_type;
  _Vel_req_type Vel_req;

   typedef double _Angle_req_type;
  _Angle_req_type Angle_req;

   typedef int32_t _Gear_req_type;
  _Gear_req_type Gear_req;





  typedef boost::shared_ptr< ::control_msgs::control_req_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::control_req_<ContainerAllocator> const> ConstPtr;

}; // struct control_req_

typedef ::control_msgs::control_req_<std::allocator<void> > control_req;

typedef boost::shared_ptr< ::control_msgs::control_req > control_reqPtr;
typedef boost::shared_ptr< ::control_msgs::control_req const> control_reqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::control_req_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::control_req_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_msgs': ['/home/leiyubiao/dalian/src/tracking/messages/control_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::control_req_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::control_req_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::control_req_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::control_req_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::control_req_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::control_req_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::control_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f755ac002e0891a7af88d03d37522ace";
  }

  static const char* value(const ::control_msgs::control_req_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf755ac002e0891a7ULL;
  static const uint64_t static_value2 = 0xaf88d03d37522aceULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::control_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/control_req";
  }

  static const char* value(const ::control_msgs::control_req_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::control_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Vel_req\n\
float64 Angle_req\n\
int32 Gear_req\n\
# 0x0:P 0x1:R 0x2:N 0x3:D\n\
";
  }

  static const char* value(const ::control_msgs::control_req_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::control_req_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Vel_req);
      stream.next(m.Angle_req);
      stream.next(m.Gear_req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_req_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::control_req_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::control_req_<ContainerAllocator>& v)
  {
    s << indent << "Vel_req: ";
    Printer<double>::stream(s, indent + "  ", v.Vel_req);
    s << indent << "Angle_req: ";
    Printer<double>::stream(s, indent + "  ", v.Angle_req);
    s << indent << "Gear_req: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Gear_req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_CONTROL_REQ_H
