// Generated by gencpp from file control_msgs/remote_signal.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_REMOTE_SIGNAL_H
#define CONTROL_MSGS_MESSAGE_REMOTE_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_msgs
{
template <class ContainerAllocator>
struct remote_signal_
{
  typedef remote_signal_<ContainerAllocator> Type;

  remote_signal_()
    : description()
    , remoteSig(0)  {
    }
  remote_signal_(const ContainerAllocator& _alloc)
    : description(_alloc)
    , remoteSig(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef int64_t _remoteSig_type;
  _remoteSig_type remoteSig;





  typedef boost::shared_ptr< ::control_msgs::remote_signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::remote_signal_<ContainerAllocator> const> ConstPtr;

}; // struct remote_signal_

typedef ::control_msgs::remote_signal_<std::allocator<void> > remote_signal;

typedef boost::shared_ptr< ::control_msgs::remote_signal > remote_signalPtr;
typedef boost::shared_ptr< ::control_msgs::remote_signal const> remote_signalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::remote_signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::remote_signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_msgs': ['/home/leiyubiao/dalian/src/tracking/messages/control_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::remote_signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::remote_signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::remote_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::remote_signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::remote_signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::remote_signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::remote_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef064086b30dd0b129639e1bf28f6fd1";
  }

  static const char* value(const ::control_msgs::remote_signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef064086b30dd0b1ULL;
  static const uint64_t static_value2 = 0x29639e1bf28f6fd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::remote_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/remote_signal";
  }

  static const char* value(const ::control_msgs::remote_signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::remote_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string description\n\
int64 remoteSig\n\
";
  }

  static const char* value(const ::control_msgs::remote_signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::remote_signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.description);
      stream.next(m.remoteSig);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remote_signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::remote_signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::remote_signal_<ContainerAllocator>& v)
  {
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "remoteSig: ";
    Printer<int64_t>::stream(s, indent + "  ", v.remoteSig);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_REMOTE_SIGNAL_H
